#Glance Install and Configuration

- name: Installing Glance Package
  apt:
    name:
      - glance
    state: latest

- name: Editing Glance [database] In Configuration File
  lineinfile:
        dest: /etc/glance/glance-api.conf
        insertafter: '\[database\]'
        regexp: '^connection = mysql+pymysql://glance:GLANCE_DBPASS@controller/glance'
        line: 'connection = mysql+pymysql://glance:pass123@controller/glance'
        state: present
        backup: yes
        backrefs: yes

- name: Editing Glance [keystone_authoken] In Configuration File
  lineinfile:
        dest: /etc/glance/glance-api.conf
        insertafter: '\[keystone_authtoken\]'
        line: "{{ item  }}"
        state: present
        backup: yes
  with_items:
        - www_authenticate_uri = http://controller:5000
        - auth_url = http://controller:5000
        - memcached_servers = controller:11211
        - auth_type = password
        - project_domain_name = Default
        - user_domain_name = Default
        - project_name = service
        - username = glance
        - password = pass123

- name: Editing Glance [paste_deploy] In Configuration File
  lineinfile:
        dest: /etc/glance/glance-api.conf
        insertafter: '\[paste_deploy\]'
        line: 'flavor = keystone'
        backup: yes


- name: Editing Glance [glance_store] In Configuration File
  lineinfile:
        dest: /etc/glance/glance-api.conf
        insertafter: '\[glance_store\]'
        line: "{{ item  }}"
        state: present
        backup: yes
  with_items:
        - stores = file,http
        - default_store = file
        - filesystem_store_datadir = /var/lib/glance/images/

- name: Editing Glance [oslo_limit] In Configuration File
  lineinfile:
        dest: /etc/glance/glance-api.conf
        insertafter: '\[oslo_limit\]'
        line: "{{ item  }}"
        state: present
        backup: yes
  with_items:
        - auth_url = http://controller:5000
        - auth_type = password
        - user_domain_id = default
        - username = MY_SERVICE
        - system_scope = all
        - password = MY_PASSWORD
        - endpoint_id = ENDPOINT_ID
        - region_name = RegionOne

#- name: Grant Reader Access to My Service Account
 # shell: 
   # sudo openstack role add --user MY_SERVICE --user-domain Default --system all reader

- name: Editing Glance [DEFAULT] In Configuration File
  lineinfile:
        dest: /etc/glance/glance-api.conf
        insertafter: '\[DEFAULT\]'
        line: 'use_keystone_limits = True'
        backup: yes

- name: Populating The Image Service Database
  shell: 
    sudo glance-manage db_sync

- name: Restart Glance Service
  service:
    name: glance-api
    state: restarted
    enabled: true
